version: '3.8'
services:
  fronted:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
    container_name: next-example
    stdin_open: true
    tty: true
